-- MySQL Script generated by MySQL Workbench
-- Wed Sep 16 10:31:38 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema rica_cocina
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema rica_cocina
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `rica_cocina` DEFAULT CHARACTER SET utf8 ;
USE `rica_cocina` ;

-- -----------------------------------------------------
-- Table `rica_cocina`.`tblmunicipio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rica_cocina`.`tblmunicipio` (
  `municipioid` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`municipioid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE UNIQUE INDEX `nombre_UNIQUE` ON `rica_cocina`.`tblmunicipio` (`nombre` ASC);


-- -----------------------------------------------------
-- Table `rica_cocina`.`tblusuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rica_cocina`.`tblusuario` (
  `usuarioid` INT(11) NOT NULL AUTO_INCREMENT,
  `Nombres` VARCHAR(50) NOT NULL,
  `apellidos` VARCHAR(50) NOT NULL,
  `fechanacimiento` DATE NOT NULL,
  `municipioid` INT(11) NOT NULL,
  PRIMARY KEY (`usuarioid`),
  CONSTRAINT `fk_tblusuario_tblmunicipio1`
    FOREIGN KEY (`municipioid`)
    REFERENCES `rica_cocina`.`tblmunicipio` (`municipioid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_tblusuario_tblmunicipio1` ON `rica_cocina`.`tblusuario` (`municipioid` ASC) ;


-- -----------------------------------------------------
-- Table `rica_cocina`.`tblroles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rica_cocina`.`tblroles` (
  `tiporolid` TINYINT(4) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `menu` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`tiporolid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `rica_cocina`.`tblcuenta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rica_cocina`.`tblcuenta` (
  `cuentaid` INT(11) NOT NULL AUTO_INCREMENT,
  `correoelectronico` VARCHAR(50) NOT NULL,
  `password` VARCHAR(150) NOT NULL,
  `tiporolid` TINYINT(4) NOT NULL,
  `estado` BIT(1) NOT NULL,
  `usuarioid` INT(11) NOT NULL,
  PRIMARY KEY (`cuentaid`),
  CONSTRAINT `fk_tblcuenta_tblusuario1`
    FOREIGN KEY (`usuarioid`)
    REFERENCES `rica_cocina`.`tblusuario` (`usuarioid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tblcuenta_tblroles1`
    FOREIGN KEY (`tiporolid`)
    REFERENCES `rica_cocina`.`tblroles` (`tiporolid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE UNIQUE INDEX `correoelectronico_UNIQUE` ON `rica_cocina`.`tblcuenta` (`correoelectronico` ASC) ;

CREATE INDEX `fk_tblcuenta_tblusuario1` ON `rica_cocina`.`tblcuenta` (`usuarioid` ASC);

CREATE INDEX `fk_tblcuenta_tblroles1` ON `rica_cocina`.`tblcuenta` (`tiporolid` ASC) ;


-- -----------------------------------------------------
-- Table `rica_cocina`.`tblpadecimiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rica_cocina`.`tblpadecimiento` (
  `padecimientoid` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`padecimientoid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE UNIQUE INDEX `nombre_UNIQUE` ON `rica_cocina`.`tblpadecimiento` (`nombre` ASC) ;


-- -----------------------------------------------------
-- Table `rica_cocina`.`tblpais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rica_cocina`.`tblpais` (
  `paisid` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`paisid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE UNIQUE INDEX `nombre_UNIQUE` ON `rica_cocina`.`tblpais` (`nombre` ASC);


-- -----------------------------------------------------
-- Table `rica_cocina`.`tbltipocomida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rica_cocina`.`tbltipocomida` (
  `tipocomidaid` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`tipocomidaid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE UNIQUE INDEX `nombre_UNIQUE` ON `rica_cocina`.`tbltipocomida` (`nombre` ASC) ;


-- -----------------------------------------------------
-- Table `rica_cocina`.`tbltipodieta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rica_cocina`.`tbltipodieta` (
  `tipodietaid` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`tipodietaid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE UNIQUE INDEX `nombre_UNIQUE` ON `rica_cocina`.`tbltipodieta` (`nombre` ASC);


-- -----------------------------------------------------
-- Table `rica_cocina`.`tblreceta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rica_cocina`.`tblreceta` (
  `recetaid` INT(11) NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NOT NULL,
  `imagen` LONGBLOB NULL DEFAULT NULL,
  `ingrediente` VARCHAR(1000) NOT NULL,
  `pasos` VARCHAR(5000) NOT NULL,
  `cantidadpersonas` VARCHAR(45) NOT NULL,
  `tiempopreparacion` VARCHAR(45) NOT NULL,
  `ocacion` VARCHAR(45) NULL DEFAULT NULL,
  `tiporeceta` VARCHAR(45) NOT NULL,
  `tipocomidaid` INT(11) NOT NULL,
  `padecimientoid` INT(11) NOT NULL,
  `tipodietaid` INT(11) NOT NULL,
  `validar` VARCHAR(45) NOT NULL,
  `usuarioid` INT(11) NOT NULL,
  `paisid` INT(11) NOT NULL,
  `votacionacomulada` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`recetaid`),
  CONSTRAINT `fk_tblreceta_tblpadecimiento1`
    FOREIGN KEY (`padecimientoid`)
    REFERENCES `rica_cocina`.`tblpadecimiento` (`padecimientoid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tblreceta_tblpais1`
    FOREIGN KEY (`paisid`)
    REFERENCES `rica_cocina`.`tblpais` (`paisid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tblreceta_tbltipocomida1`
    FOREIGN KEY (`tipocomidaid`)
    REFERENCES `rica_cocina`.`tbltipocomida` (`tipocomidaid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tblreceta_tbltipodieta1`
    FOREIGN KEY (`tipodietaid`)
    REFERENCES `rica_cocina`.`tbltipodieta` (`tipodietaid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tblreceta_tblusuario1`
    FOREIGN KEY (`usuarioid`)
    REFERENCES `rica_cocina`.`tblusuario` (`usuarioid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_tblreceta_tblpais1` ON `rica_cocina`.`tblreceta` (`paisid` ASC) ;

CREATE INDEX `fk_tblreceta_tblusuario1` ON `rica_cocina`.`tblreceta` (`usuarioid` ASC) ;

CREATE INDEX `fk_tblreceta_tbltipodieta1` ON `rica_cocina`.`tblreceta` (`tipodietaid` ASC) ;

CREATE INDEX `fk_tblreceta_tblpadecimiento1` ON `rica_cocina`.`tblreceta` (`padecimientoid` ASC) ;

CREATE INDEX `fk_tblreceta_tbltipocomida1` ON `rica_cocina`.`tblreceta` (`tipocomidaid` ASC) ;


-- -----------------------------------------------------
-- Table `rica_cocina`.`tblutensilios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rica_cocina`.`tblutensilios` (
  `utensilioid` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`utensilioid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE UNIQUE INDEX `nombre` ON `rica_cocina`.`tblutensilios` (`nombre` ASC) ;


-- -----------------------------------------------------
-- Table `rica_cocina`.`tblrecetautensilio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rica_cocina`.`tblrecetautensilio` (
  `utensilioid` INT(11) NOT NULL,
  `recetaid` INT(11) NOT NULL,
  PRIMARY KEY (`utensilioid`, `recetaid`),
  CONSTRAINT `fk_tblutensilios_has_tblreceta_tblreceta1`
    FOREIGN KEY (`recetaid`)
    REFERENCES `rica_cocina`.`tblreceta` (`recetaid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tblutensilios_has_tblreceta_tblutensilios1`
    FOREIGN KEY (`utensilioid`)
    REFERENCES `rica_cocina`.`tblutensilios` (`utensilioid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_tblutensilios_has_tblreceta_tblreceta1` ON `rica_cocina`.`tblrecetautensilio` (`recetaid` ASC);



-- -----------------------------------------------------
-- Table `rica_cocina`.`tblretroalimentacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rica_cocina`.`tblretroalimentacion` (
  `retroalimentacionid` INT(11) NOT NULL AUTO_INCREMENT,
  `texto` VARCHAR(300) NULL DEFAULT NULL,
  `recetaid` INT(11) NOT NULL,
  `fecha` DATE NOT NULL,
  `usuarioid` INT(11) NOT NULL,
  PRIMARY KEY (`retroalimentacionid`),
  CONSTRAINT `fk_tblretroalimentacion_tblreceta`
    FOREIGN KEY (`recetaid`)
    REFERENCES `rica_cocina`.`tblreceta` (`recetaid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tblretroalimentacion_tblusuario1`
    FOREIGN KEY (`usuarioid`)
    REFERENCES `rica_cocina`.`tblusuario` (`usuarioid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_tblretroalimentacion_tblreceta` ON `rica_cocina`.`tblretroalimentacion` (`recetaid` ASC) ;

CREATE INDEX `fk_tblretroalimentacion_tblusuario1` ON `rica_cocina`.`tblretroalimentacion` (`usuarioid` ASC) ;



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
